
apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: elkesstack
  labels:
    app: elkes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elkes
  template:
    metadata:
      labels:
        app: elkes
    spec:
      containers:
       - name: elkes
         image: docker.elastic.co/elasticsearch/elasticsearch:6.0.1
         ports:
          - containerPort: 9200
          - containerPort: 9300
         env:
          - name: discovery.type
            value: single-node
       - name: elkkibana
         image: docker.elastic.co/kibana/kibana:6.0.1
         ports:
          - containerPort: 5601
         env:
          - name: ELASTICSEARCH_URL
            value: http://localhost:9200
       - name: logstatsh
         image: docker.io/nagareddy/loghauler:1.4
         volumeMounts:
         - mountPath: /data/logs
           name: logsvolume
      volumes:
       - name: esdata
         hostPath:
          path: /home/docker/elkdata/esdata
          type: Directory
       - name: logsvolume
         hostPath:
          path: /home/docker/elkdata/logs
          type: Directory
