
apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: hellod
  labels:
    app: helloworld
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hellod
  template:
    metadata:
      labels:
        app: hellod
    spec:
      containers:
       - name: helloapp
         image: docker.io/nagareddy/hellogo:v5
         command: ["/go/bin/helloworld"]
         ports:
          - containerPort: 8080
         volumeMounts:
         - mountPath: /data/samplevol
           name: samplevol
      volumes:
       - name: samplevol
         hostPath:
          path: /home/docker/elkdata
          type: Directory
