
apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: ReplicaSet
metadata:
  name: hellopodrset
  labels:
    app: helloworld
    tier: frontend
spec:
  # this replicas value is default
  # modify it according to your case
  replicas: 2
  selector:
    matchLabels:
      tier: frontend
    matchExpressions:
      - {key: tier, operator: In, values: [frontend]}
  template:
    metadata:
      labels:
        app: hellopodrset
        tier: frontend
    spec:
      containers:
      - name: helloworldrset
        image: docker.io/nagareddy/hellogo:v5
        command: ["/go/bin/helloworld"]
        env:
        - name: GET_HOSTS_FROM
          value: dns
          # If your cluster config does not include a dns service, then to
          # instead access environment variables to find service host
          # info, comment out the 'value: dns' line above, and uncomment the
          # line below.
          # value: env
        ports:
        - containerPort: 8080

