apiVersion: v1
kind: Pod
metadata:
  name: helloworld 
spec:
  containers:
  - name: escrawlkc
    image: docker.io/nagareddy/hellogo:v5
    command: ["/go/bin/helloworld"]
    ports:
     - containerPort: 8080
