
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: hellocmdcronjob
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hellocmdcronjob
            image: docker.io/nagareddy/hellogo:v6
            command: ["/go/bin/hellocmd"]
          restartPolicy: OnFailure

